# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "app-dev"
    key                  = "./terraform.tfstate"
    resource_group_name  = "rg-app-dev-tf-frc1-001"
    storage_account_name = "stjtappdevtffrc1001"
    use_azuread_auth     = true
  }
}
