on:
  workflow_call:
    inputs:
      terraform-version:
        required: false
        type: string
        default: '1.5.1'
      terragrunt-version:
        required: false
        type: string
        default: '0.42.2'
      terragrunt-working-dir:
        required: true
        type: string
      environment:
        required: true
        type: string
      log-level:
        required: false
        type: string
        default: 'INFO'
    secrets:
      GH_TOKEN:
        required: true
      BUCKET_NAME:
        required: true
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      AWS_ROLE_NAME:
        required: true
      AWS_SESSION_NAME:
        required: true

permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  TERRAFORM_VERSION: ${{ inputs.terraform-version }}
  TERRAGRUNT_VERSION: ${{ inputs.terragrunt-version }}
  TERRAGRUNT_WORKING_DIR: ${{ inputs.terragrunt-working-dir }}
  TF_LOG: ${{ inputs.log-level }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
  AWS_SESSION_NAME: ${{ secrets.AWS_SESSION_NAME }}

jobs:
  terragrunt-plan:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to AWS using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
        role-session-name: ${{ env.AWS_SESSION_NAME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Terraform ${{ env.TERRAFORM_VERSION }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false

    - name: Setup Terragrunt ${{ env.TERRAGRUNT_VERSION }}
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: ${{ env.TERRAGRUNT_VERSION }}

    - name: Terragrunt Format
      run: |
       terragrunt fmt --terragrunt-working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}

    - name: Terragrunt Init
      run: |
       terragrunt init --terragrunt-working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}

    - name: Terragrunt Validate
      run: |
       terragrunt validate --terragrunt-working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}

    - name: Terragrunt Plan
      run: |
       terragrunt plan --terragrunt-working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}
