on:
  push:
    branches:
      - main
    paths:
      - 'aws/master/ipam**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-apply-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/blob/main/actions/aws-terragrunt-apply.yaml@main
    with:
      terragrunt-working-dir: './aws/master/ipam'
      environment: aws.master.ipam.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
