on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'aws/master/oidc**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-plan-workflow:
    uses: ./.github/workflows/aws.terragrunt-plan.yaml
    with:
      terragrunt-working-dir: './aws/master/oidc'
      environment: aws.master.oidc.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
