on:
  push:
    branches:
      - main
    paths:
      - 'azure/connectivity/dev/westeurope/multitenant/virtual-wan**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-apply-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/azure-terragrunt-apply-template.yaml@main
    with:
      terragrunt-working-dir: './azure/connectivity/dev/westeurope/multitenant/virtual-wan'
      environment: connectivity.dev.virtual-wan.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
