on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'azure/app/prod/key-vault**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-plan-workflow:
    uses: ./.github/workflows/azure.terragrunt-plan.yaml
    with:
      terragrunt-working-dir: './azure/app/prod/key-vault'
      environment: app.prod.key-vault.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
