on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'azure/connectivity/dev/westeurope/multitenant/virtual-hub**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-plan-workflow:
    strategy:
        matrix:
          region: [westeurope]
    steps:
      - uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/azure-terragrunt-plan-template.yaml@main
        with:
          terragrunt-working-dir: './azure/connectivity/dev/westeurope/multitenant/virtual-hub'
          environment: connectivity.dev.virtual-hub.deploy
          log-level: ${{ inputs.logLevel }}
  secrets: inherit
