on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'azure/management/prod/westeurope/multitenant/logging/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-plan-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/azure-terragrunt-plan-template.yaml@main
    strategy:
        matrix:
          region: [westeurope]
    with:
      terragrunt-working-dir: './azure/management/prod/${{ matrix.region }}/multitenant/logging'
      environment: management.prod.logging.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
