on:
  push:
    branches:
      - main
    paths:
      - 'azure/app/dev/westeurope/multitenant/app-gateway**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-apply-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/azure-terragrunt-apply-template.yaml@main
    with:
      terragrunt-working-dir: './azure/app/dev/westeurope/multitenant/app-gateway'
      environment: app.dev.app-gateway.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
