on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'azure/setup/prod/landing-zones-storage/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-plan-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/azure-terragrunt-run-all-plan-template.yaml@main
    with:
      terragrunt-working-dir: './azure/setup/prod/landing-zones-storage'
      environment: azure.setup.prod.landing-zones.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
