on:
  push:
    branches:
      - main
    paths:
      - 'azure/identity/shared/identities**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-apply-workflow:
    uses: ./.github/workflows/azure.terragrunt-apply.yaml
    with:
      terragrunt-working-dir: './azure/identity/shared/identities'
      environment: identity.shared.identities.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
