on:
  push:
    branches:
      - main
    paths:
      - 'azure/connectivity/dev/westeurope/multitenant/dns-resolver**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-apply-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/azure-terragrunt-run-all-apply-template.yaml@main
    strategy:
        matrix:
          region: [westeurope]
    with:
      terragrunt-working-dir: './azure/connectivity/dev/${{ matrix.region }}/multitenant/dns-resolver'
      environment: connectivity.dev.dns-resolver.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
