on:
  push:
    branches:
      - main
    paths:
      - 'azure/app/prod/westeurope/multitenant/sql-server**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-apply-workflow:
    uses: JamieTaffurelliOrg/github-actions-templates/.github/workflows/azure-terragrunt-apply-template.yaml@main
    strategy:
        matrix:
          region: [westeurope]
    with:
      terragrunt-working-dir: './azure/app/prod/${{ matrix.region }}/multitenant/sql-server'
      environment: app.prod.sql-server.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
