on:
  push:
    branches:
      - main
    paths:
      - 'azure/setup/prod/resource-groups/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  call-terraform-apply-workflow:
    uses: ./.github/workflows/azure.terragrunt-run-all-apply.yaml
    with:
      terragrunt-working-dir: './azure/setup/prod/resource-groups'
      environment: azure.setup.prod.landing-zones.deploy
      log-level: ${{ inputs.logLevel }}
    secrets: inherit
