on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'github/JamieTaffurelliOrg/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - WARNING
        - DEBUG

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  TERRAFORM_VERSION: '1.3.9'
  TERRAGRUNT_VERSION: '0.42.2'
  TERRAGRUNT_WORKING_DIR: './github/JamieTaffurelliOrg'
  TF_LOG: ${{ inputs.logLevel }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true

jobs:
  terragrunt-plan:
    environment: github.jamietaffurelliorg.deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install Terraform ${{ env.TERRAFORM_VERSION }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false

    - name: Setup Terragrunt ${{ env.TERRAGRUNT_VERSION }}
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: ${{ env.TERRAGRUNT_VERSION }}

    - name: Terragrunt Format
      run: |
       terragrunt fmt --terragrunt-working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}

    - name: Terragrunt Init
      run: |
       terragrunt init --terragrunt-working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}

    - name: Terragrunt Validate
      run: |
       terragrunt validate --terragrunt-working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}

    - name: Terragrunt Plan
      run: |
       terragrunt plan --terragrunt-working-dir ${{ env.TERRAGRUNT_WORKING_DIR }}
