on: pull_request

concurrency: ci-${{ github.ref }}

env:
  TERRAGRUNT_VERSION: '0.38.4'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: ${{ env.TERRAGRUNT_VERSION }}

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: -v --all-files
